apiVersion: 1
datasources:
  - access: proxy
    basicAuth: false
    editable: false
    isDefault: false
    jsonData: {}
    name: Prometheus
    orgId: 1
    type: prometheus
    url: http://prometheus:9090
    version: 1
