networks:
  overlay:
    name: overlay
services:
  alertmanager:
    command:
      - --config.file=/etc/alertmanager/config.yml
      - --storage.path=/alertmanager
    devices: []
    environment: []
    image: prom/alertmanager:v0.21.0
    networks:
      - overlay
    ports:
      - 9093:9093/tcp
    restart: always
    volumes:
      - ./config/alertmanager/:/etc/alertmanager:rw
      - ./config/alertmanager_templates/:/etc/alertmanager-templates:rw
      - ./volume/alertmanager/:/alertmanager:rw
  karma:
    devices: []
    environment:
    - CONFIG_FILE=/config/karma.yml
    - ALERTMANAGER_URI=http://alertmanager:9093
    image: docker.io/lmierzwa/karma:v0.70
    network_mode: host
    ports:
      - 8082:8082/tcp
    restart: always
    volumes:
      - ./config/karma/:/config/:rw
  blackbox-exporter:
    command:
      - --config.file=/etc/blackbox-exporter/config.yml
    devices: []
    environment: []
    image: prom/blackbox-exporter:v0.17.0
    networks:
      - overlay
    ports:
      - 9115:9115/tcp
    restart: always
    volumes:
      - ./config/blackbox_exporter/:/etc/blackbox-exporter:rw
  cloudprober:
    command:
      - --config_file=/etc/cloudprober/cloudprober.cfg
    devices: []
    environment: []
    image: cloudprober/cloudprober:v0.10.9
    networks:
      - overlay
    ports:
      - 9313:9313/tcp
    restart: always
    volumes:
      - ./config/cloudprober/:/etc/cloudprober:rw
  cadvisor:
    command: []
    devices: []
    environment: []
    image: google/cadvisor:v0.33.0
    networks:
      - overlay
    ports:
      - 8080:8080/tcp
    restart: always
    volumes:
      - /var/lib/docker:/var/lib/docker:ro
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
  grafana:
    command: []
    devices: []
    environment:
      - GF_INSTALL_PLUGINS=grafana-clock-panel,grafana-worldmap-panel,natel-discrete-panel,jdbranham-diagram-panel,neocat-cal-heatmap-panel,grafana-simple-json-datasource,grafana-azure-monitor-datasource,camptocamp-prometheus-alertmanager-datasource
      - GF_PATHS_PROVISIONING=/etc/grafana/provisioning
      - GF_SECURITY_ADMIN_PASSWORD=heslo
      - GF_SECURITY_ADMIN_USER=admin
      - GF_USERS_ALLOW_SIGN_UP=false
    image: grafana/grafana:7.2.0
    networks:
      - overlay
    ports:
      - 3000:3000/tcp
    restart: always
    volumes:
      - ./config/grafana_provision_dashboards/:/etc/grafana/provisioning/dashboards:rw
      - ./config/grafana_dashboards/:/var/lib/grafana/dashboards:rw
      - ./config/grafana_provision_datasources/:/etc/grafana/provisioning/datasources:rw
      - ./volume/grafana/:/var/lib/grafana:rw
  node-exporter:
    command:
      - --path.procfs=/host/proc
      - --path.sysfs=/host/sys
      - --collector.filesystem.ignored-mount-points
      - ^/(sys|proc|dev|host|etc|rootfs/var/lib/docker/containers|rootfs/var/lib/docker/overlay2|rootfs/run/docker/netns|rootfs/var/lib/docker/aufs)($$|/)
    devices: []
    environment: []
    image: prom/node-exporter:v1.0.1
    networks:
      - overlay
    ports:
      - 9100:9100/tcp
    restart: always
    volumes:
      - /proc:/host/proc:ro
      - /:/rootfs:ro
      - /sys:/host/sys:ro
  prometheus:
    command:
      - --config.file=/etc/prometheus/prometheus.yaml
      - --storage.tsdb.path=/data
      - --storage.tsdb.retention=14d
      - --web.enable-lifecycle
    devices: []
    environment: []
    image: prom/prometheus:v2.21.0
    networks:
      - overlay
    ports:
      - 9090:9090/tcp
    restart: always
    volumes:
      - ./config/prometheus_rules/:/etc/prometheus-rules/:rw
      - ./config/prometheus/:/etc/prometheus/:rw
      - ./volume/prometheus/:/data:rw
  nasa-swpc-exporter:
    command: []
    devices: []
    environment: []
    image: cznewt/nasa-swpc-exporter:latest
    networks:
      - overlay
    ports:
      - 9468:9468/tcp
    restart: always
  statsd-exporter:
    command:
      - --statsd.mapping-config=/etc/statsd-exporter/mapping.yml
    devices: []
    environment: []
    image: prom/statsd-exporter:v0.7.0
    networks:
      - overlay
    ports:
      - 9102:9102/tcp
      - 9125:9125/tcp
      - 9125:9125/udp
    restart: always
    volumes:
      - ./config/statsd_exporter/:/etc/statsd-exporter/:rw
version: '3.5'
volumes: {}