mappings:
  - labels:
      location: $1
    match: epdor.*.*
    name: epdor_${2}
  - labels:
      aggregation: avg
      device: $2
      location: $1
    match: '*.*.*.avg_value'
    name: robophery_${3}
  - labels:
      aggregation: min
      device: $2
      location: $1
    match: '*.*.*.min_value'
    name: robophery_${3}
  - labels:
      aggregation: max
      device: $2
      location: $1
    match: '*.*.*.max_value'
    name: robophery_${3}
  - labels:
      device: $2
      location: $1
      metric: $3
    match: '*.*.*.read_time'
    name: robophery_metric_read_time
  - labels:
      device: $2
      location: $1
      metric: $3
    match: '*.*.*.error_rate'
    name: robophery_metric_error_rate
