{
 "title": "Solar Wind (NOAA DSCOVR)",
 "tags": [
  "nasa_swpc_exporter",
  "prometheus_ds"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "PROMETHEUS_DS", "label": "Data Source", "query": "prometheus" },
   {
    "name": "job",
    "label": "Job",
    "query": "label_values(solar_wind_speed, job)"
   }
  ]
 },
 "panels": [
  {
   "title": "Current Solar Wind Speed",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "solar_wind_speed{job=~\"$job\"}"
    }
   ]
  },
  {
   "title": "Solar Wind Speed History",
   "type": "graph",
   "gridPos": { "h": 5, "w": 18, "x": 6, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "solar_wind_speed{job=~\"$job\"}",
     "legendFormat": "solar wind speed"
    }
   ]
  },
  {
   "title": "Current Solar Wind Density",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 5 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "solar_wind_density{job=~\"$job\"}"
    }
   ]
  },
  {
   "title": "Solar Wind Density History",
   "type": "graph",
   "gridPos": { "h": 5, "w": 18, "x": 6, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "solar_wind_density{job=~\"$job\"}",
     "legendFormat": "solar wind density"
    }
   ]
  },
  {
   "title": "Current Solar Wind Temperature",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 10 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "solar_wind_temperature{job=~\"$job\"}"
    }
   ]
  },
  {
   "title": "Solar Wind Temperature History",
   "type": "graph",
   "gridPos": { "h": 5, "w": 18, "x": 6, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "solar_wind_temperature{job=~\"$job\"}",
     "legendFormat": "solar wind temperature"
    }
   ]
  }
 ]
}