{
   "groups": [
      {
         "name": "demo",
         "rules": [
            {
               "alert": "NodeLoadHigh",
               "annotations": {
                  "description": "Node {{ $labels.instance }} has load {{ $value }} for more than 30 minutes.",
                  "summary": "Node has too high load."
               },
               "expr": "instance:node_load1_per_cpu:ratio > 1\n",
               "for": "30m",
               "labels": {
                  "severity": "warning"
               }
            },
            {
               "alert": "NodeLoadHigh",
               "annotations": {
                  "description": "Node {{ $labels.instance }} has load {{ $value }} for more than 30 minutes.",
                  "summary": "Node has too high load."
               },
               "expr": "instance:node_load1_per_cpu:ratio > 2\n",
               "for": "1h",
               "labels": {
                  "severity": "critical"
               }
            }
         ]
      }
   ]
}