{
   "groups": [
      {
         "name": "logging_elasticsearch.alerts",
         "rules": [
            {
               "alert": "ElasticsearchClusterNotHealthy",
               "annotations": {
                  "message": "Cluster {{ $labels.cluster }} health status has been RED for at least 2m. Cluster does not accept writes, shards may be missing or master node hasn't been elected yet.",
                  "summary": "Cluster health status is RED"
               },
               "expr": "sum by (cluster) (es_cluster_status == 2)\n",
               "for": "2m",
               "labels": {
                  "severity": "critical"
               }
            },
            {
               "alert": "ElasticsearchClusterNotHealthy",
               "annotations": {
                  "message": "Cluster {{ $labels.cluster }} health status has been YELLOW for at least 20m. Some shard replicas are not allocated.",
                  "summary": "Cluster health status is YELLOW"
               },
               "expr": "sum by (cluster) (es_cluster_status == 1)\n",
               "for": "20m",
               "labels": {
                  "severity": "warning"
               }
            },
            {
               "alert": "ElasticsearchBulkRequestsRejectionJumps",
               "annotations": {
                  "message": "High Bulk Rejection Ratio at {{ $labels.node }} node in {{ $labels.cluster }} cluster. This node may not be keeping up with the indexing speed.",
                  "summary": "High Bulk Rejection Ratio - {{ $value }}%"
               },
               "expr": "round( bulk:reject_ratio:rate2m * 100, 0.001 ) > 5\n",
               "for": "10m",
               "labels": {
                  "severity": "warning"
               }
            },
            {
               "alert": "ElasticsearchNodeDiskWatermarkReached",
               "annotations": {
                  "message": "Disk Low Watermark Reached at {{ $labels.node }} node in {{ $labels.cluster }} cluster. Shards can not be allocated to this node anymore. You should consider adding more disk to the node.",
                  "summary": "Disk Low Watermark Reached - disk saturation is {{ $value }}%"
               },
               "expr": "sum by (cluster, instance, node) (\n  round(\n    (1 - (\n      es_fs_path_available_bytes /\n      es_fs_path_total_bytes\n    )\n  ) * 100, 0.001)\n) > 85\n",
               "for": "5m",
               "labels": {
                  "severity": "alert"
               }
            },
            {
               "alert": "ElasticsearchNodeDiskWatermarkReached",
               "annotations": {
                  "message": "Disk High Watermark Reached at {{ $labels.node }} node in {{ $labels.cluster }} cluster. Some shards will be re-allocated to different nodes if possible. Make sure more disk space is added to the node or drop old indices allocated to this node.",
                  "summary": "Disk High Watermark Reached - disk saturation is {{ $value }}%"
               },
               "expr": "sum by (cluster, instance, node) (\n  round(\n    (1 - (\n      es_fs_path_available_bytes /\n      es_fs_path_total_bytes\n    )\n  ) * 100, 0.001)\n) > 90\n",
               "for": "5m",
               "labels": {
                  "severity": "high"
               }
            },
            {
               "alert": "ElasticsearchJVMHeapUseHigh",
               "annotations": {
                  "message": "JVM Heap usage on the node {{ $labels.node }} in {{ $labels.cluster }} cluster is {{ $value }}%.",
                  "summary": "JVM Heap usage on the node is high"
               },
               "expr": "sum by (cluster, instance, node) (es_jvm_mem_heap_used_percent) > 75\n",
               "for": "10m",
               "labels": {
                  "severity": "alert"
               }
            },
            {
               "alert": "AggregatedLoggingSystemCPUHigh",
               "annotations": {
                  "message": "System CPU usage on the node {{ $labels.node }} in {{ $labels.cluster }} cluster is {{ $value }}%",
                  "summary": "System CPU usage is high"
               },
               "expr": "sum by (cluster, instance, node) (es_os_cpu_percent) > 90\n",
               "for": "1m",
               "labels": {
                  "severity": "alert"
               }
            },
            {
               "alert": "ElasticsearchProcessCPUHigh",
               "annotations": {
                  "message": "ES process CPU usage on the node {{ $labels.node }} in {{ $labels.cluster }} cluster is {{ $value }}%",
                  "summary": "ES process CPU usage is high"
               },
               "expr": "sum by (cluster, instance, node) (es_process_cpu_percent) > 90\n",
               "for": "1m",
               "labels": {
                  "severity": "alert"
               }
            }
         ]
      }
   ]
}